image: docker:19.03.0

stages:
  - build-push-image
  - deploy-image

cache:
  paths:
    - .yarn

variables:
  CONTAINER_IMAGE_MASTER: $DOCKER_REGISTRY_URI/roomfix-api:${CI_COMMIT_SHORT_SHA}

build-master:
  services:
    - docker:19.03.0-dind
  stage: build-push-image
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URI
    - docker build -t $CONTAINER_IMAGE_MASTER .
    - docker push $CONTAINER_IMAGE_MASTER
  only:
    - master

deploy-image-master:
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  stage: deploy-image
  script:
    - cat $KUBERNETES_CONFIG | base64 -d > ./kubeconfig
    - kubectl set image deployment roomfix-api-master roomfix-api-master=$CONTAINER_IMAGE_MASTER --kubeconfig ./kubeconfig --namespace default
  only:
    - master
  cache: {}


    